require 'hoe'
require './lib/catalogdb/version.rb'

Hoe.spec 'catalogdb' do

  self.version = CatalogDb::VERSION

  self.summary = "catalogdb - catalog.db schema 'n' models for easy (re)use"
  self.description = summary

  self.urls    = ['https://github.com/textkit/catalog.db']

  self.author  = 'Gerald Bauer'
  self.email   = 'ruby-talk@ruby-lang.org'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'HISTORY.md'

  self.extra_deps = [
    ['props', '>= 1.1.2'], # settings / prop(ertie)s / env / INI
    ['logutils', '>= 0.6.1'], # logging
    ['textutils', '>= 1.3.1'],

    ## 3rd party
    ['activerecord'], # NB: will include activesupport,etc.

    ## more activerecord utils/addons
    ## ['tagutils', '>= 0.3.0'], # tags n categories for activerecord
    ## ['activerecord-utils', '>= 0.4.0'],
    ['props-activerecord', '>= 0.1.0'],
    ['logutils-activerecord', '>= 0.2.1'],
  ]

  self.licenses = ['Public Domain']

  self.spec_extras = {
    required_ruby_version: '>= 1.9.2'
  }

end
