require 'hoe'
require './lib/typeconv/version.rb'

Hoe.spec 'typeconv' do

  self.version = Typeconv::VERSION

  self.summary = "typeconv (type converters) - convert strings to numbers, dates, booleans, nulls and more"
  self.description = summary

  self.urls    = ['https://github.com/rubycoco/typeconv']

  self.author  = 'Gerald Bauer'
  self.email   = 'wwwmake@googlegroups.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'HISTORY.md'

  self.extra_deps = [
  ]

  self.licenses = ['Public Domain']

  self.spec_extras = {
    required_ruby_version: '>= 2.2.2'
  }

end
